### PR TITLE
Broadcast service javascript api implementation

### PR DESCRIPTION
**Pull request by larrysalibra**
This pull request adds the broadcast transaction service API documented in #362 with some slight changes to the request format:

```
      /*
       * POST /v1/broadcast/transaction
       * Request body:
       * JSON.stringify({
       *  transaction,
       *  transactionToWatch,
       *  confirmations
       * })
      */

      /*
       * POST /v1/broadcast/zone-file
       * Request body:
       * JSON.stringify({
       *  zoneFile,
       *  transactionToWatch
       * })
       */

      /*
       * POST /v1/broadcast/registration
       * Request body:
       * JSON.stringify({
       * preorderTransaction,
       * registerTransaction,
       * zoneFile
       * })
       */
```

The public developer API methods added in this pull request check to make sure the developer has passed required parameters, rejecting with an error other wise as part of making our developer API more helpful.

They also reject with an error if a remote service has an error.

As part of implementing the error handling, this PR adds a basic error framework based on a previous discussion we had https://github.com/blockstack/blockstack-core/issues/422#issue-227806997

This is something we should flesh out and further define in a future sprint.

There still needs to be a bit of work done on the specific JSON objects returned by each of these functions. At the moment it just passes whatever the API sends back.

@kantai we should sync up on what info the service will be returning. 

I've also enabled lint coverage of our test framework in this pull request. Apologies for not including this in a separate pull request.

You can test this by running the test framework until the broadcast service is complete.

### CODE REVIEW

**Comment by kantai** [comment]
This looks great (thanks for all the linting as well!) to me @larrysalibra. The integration tests are passing for me, so the changes there are okay. 

One note on this API -- should we support the zone file being optionally passed as a Base64 string?

**Comment by larrysalibra** [comment]
> One note on this API -- should we support the zone file being optionally passed as a Base64 string

What's the benefit of that?

**Comment by kantai** [comment]
Really, it would just make storing arbitrary data in the zonefile easier -- rather than trying to pass the data in a json string, it could be passed as a base64 encoding of the bytes. I am convinced this isn't necessary for now, and if we want to expand the API later we can.

**Review by kantai — APPROVED** [review]
This looks good to merge, @larrysalibra

**Pull request merged**
