### PR TITLE
Change maintainer

### PR DESCRIPTION
**Pull request by larrysalibra**
This pull request updates the README to list @yknl as the maintainer of blockstack.js.

@yknl has[ proposed a very exciting roadmap](https://forum.blockstack.org/t/proposal-developer-tools-roadmap-q1-q2-2019/6875?u=larry) for blockstack.js and our other developer tools for 2019. I can't wait to see where things go!

### CODE REVIEW

**Review by yknl — APPROVED** [review]
Thanks @larrysalibra!

**Review by kantai — APPROVED** [review]
👍

**Review by hstove — APPROVED** [review]
Larry where are the tests for this???

😛

**Comment by larrysalibra** [comment]
@hstove 
> Larry where are the tests for this???

lol!!!

**Pull request merged**
