### PR TITLE
Add `getFileUrl()`

### PR DESCRIPTION
**Pull request by kantai**
Got distracted by an old issue report #234 and decided to implement.

This adds a `getFileUrl()` function with roughly the same API as `getFile()` (minus the encryption, verification options).

```javascript
/**
 * Get the URL for reading a file from an app's data store.
 * @param {String} path - the path to the file to read
 * @param {Object} [options=null] - options object
 * @param {String} options.username - the Blockstack ID to lookup for multi-player storage
 * @param {String} options.app - the app to lookup for multi-player storage -
 * defaults to current origin
 * @param {String} [options.zoneFileLookupURL=null] - The URL
 * to use for zonefile lookup. If falsey, this will use the
 * blockstack.js's getNameInfo function instead.
 * @returns {Promise} that resolves to the URL or rejects with an error
 */
```

This _also_ refactors `getFileContents` (an internal function used by `getFile`) to use this function, which means that the tests for `getFile` now cover `getFileUrl` (so I didn't add tests).

### CODE REVIEW

**Comment by jcnelson** [comment]
Cool!  Does this also mean that you don't need to use `window` at all anymore in node.js?  i.e. does this also address https://github.com/blockstack/blockstack.js/issues/500?

**Comment by kantai** [comment]
Sort of -- only multi-player `getFile` will work without the `window` at all (everything else like `putFile` and single-player `getFile` tries to use userSession state, which would need to be refactored for non-browser contexts)

So this will work:
```javascript
const bsk = require('blockstack')
bsk.getFile('statuses.json', { username: 'collectivism.id', app: "https://app.travelstack.club", decrypt: false }).then(console.log).catch(console.log)
```

**Comment by x5engine** [comment]
>  You don't need to use window at all anymore in node.js?

The dream

**Comment by hstove** [comment]
This looks good to me - just need to resolve changelogs conflicts.

**Comment by friedger** [comment]
@kantai Can we have this merged so I can add it to the Android SDK?

**Comment by kantai** [comment]
Resolved changelog conflicts, and updated reviewer to the new maintainer of blockstack.js

**Review by yknl — APPROVED** [review]
This looks good to me 👍

**Review by zone117x — APPROVED** [review]

**Pull request merged**
