### PR TITLE
Update Eslint and Jest

### PR DESCRIPTION
**Pull request by reedrosenbluth**
Update to new versions of eslint related dependencies and Jest

### CODE REVIEW

**Comment by kyranjamie** [comment]
There are `@stacks/{eslint,prettier}-config`s now

**Comment by reedrosenbluth** [comment]
@kyranjamie does that mean these dependencies can be removed?

**Comment by kyranjamie** [comment]
Yeah, if you install the other ones and swap the references.

**Comment by agraebe** [comment]
@reedrosenbluth who should review this?

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
