### PR TITLE
[WIP] feat: add BNS package

### PR DESCRIPTION
**Pull request by yknl**
This PR adds a `@stacks/bns` library that enables interaction with the Stacks 2.0 version of the Blockchain Naming System. #864 

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
- [ ] Link to documentation updates: 

## Checklist
- [x] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [ ] Tag 1 of @yknl or @zone117x for review

### CODE REVIEW

**Comment by agraebe** [comment]
what's the next step here? @yknl @hstove ?

**Comment by yknl** [comment]
This PR needs to be updated for the new BNS endpoints from the API and adding a readme, and QA.

**Comment by diwakergupta** [comment]
We need to figure out a way to move this PR forward cc/ @agraebe 

@yknl I'm guessing you're not available to help? :)

@reedrosenbluth could you help out?

**Comment by reedrosenbluth** [comment]
@diwakergupta planning on working on this tomorrow!

**Comment by reedrosenbluth** [comment]
Closing this PR since the BN package was added here: https://github.com/blockstack/stacks.js/pull/978

**Pull request closed without merging**
