### PR TITLE
Remove console.log in resolveZoneFileToProfile

### PR DESCRIPTION
**Pull request by kantai**
I find these console.log'd errors pretty annoying, and printing things with console.log as a library is generally frowned upon.

Opening a PR to see if others agree with me :grinning:

### CODE REVIEW

**Comment by vsund** [comment]
There are quite some `console.log` calls in the code. For my [fork](https://github.com/ntzwrk/blockstack.ts) I went with a global logger class (with different log levels).
Developers can probably help themselves better (independently from where the error was made) with proper logging in place. So I think we even should move to consistent logging for cases that might confuse developers (e.g. in the `Service` classes there are some cases that might not be an error but in case of an error it might be helpful to know which path was taken).

But though I think that this could be off by default :)

**Comment by hstove** [comment]
Agreed that probably the best solution is to have different logging levels, with the ability for developers to specify which level they want to display.

**Comment by kantai** [comment]
Cool -- @hstove, want to start an issue for coming up with a logging solution? (Probably also related to #418).

Until we come up with a logging approach, do folks think we should just remove the console.logs ?

**Comment by vsund** [comment]
Would be harder to then add in logging later without all the `console.log` calls ;)

**Pull request closed without merging**
