### PR TITLE
Improve multisig readme examples #1055

### LINKED ISSUE #1055: Improve multisig readme examples
- Make the multisig readme examples more clear.
- Make sure to point out that the order in which the TX is signed makes a difference.
- Mention that both private keys *and* public keys should be in the same format (compressed or uncompressed)

### PR DESCRIPTION
**Pull request by bilalanees98**
## Description

As someone who's looking to utilise this sdk for their application it is vital that they are able to understand the how to utilise the various packages. This pull request updates the Multi-sig transaction examples in the transaction package readme in an effort to make it more clear and ensure proper understanding.

For details refer to issue #1055

## Type of Change

- [ ] New feature
- [ ] Bug fix
- [x] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?

No breaking change

## Are documentation updates required?

No.

## Testing information

None.

## Checklist

- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @yknl or @zone117x for review

### CODE REVIEW

**Comment by bilalanees98** [comment]
@reedrosenbluth Requesting a review from you.
Please grant me permissions so I can request reviews and link issues as well

**Comment by saralab** [comment]
Will create a new issue , closing this one

**Review by Thirumurugan7 — COMMENTED** [review]
include the broadcast issues too

**Comment by janniks** [comment]
Which broadcast issue is that?

**Pull request closed without merging**
