### PR TITLE
Feature/auth response 1.3

### PR DESCRIPTION
**Pull request by jcnelson**
This PR adds two new fields to `authResponse` JWTs:
* a `blockstackAPIUrl` field that, if given, overrides the global API URL in `blockstack.config.network`.  This allows the user to tell the app which Blockstack Core node they want to use.
* a `gaiaAssociationToken` field that contains an association token JWT to be passed to Gaia (see https://github.com/blockstack/gaia/issues/96).  By adding this field, we enable users to run private Gaia hubs without having to authorize each application's address.  They instead only have to authorize their user addresses, and use this code to generate a v1 Gaia authentication token with an association token that binds the app address to their user address.

This PR absorbs and supersedes https://github.com/blockstack/blockstack.js/pull/494.  Please see this PR for discussion on the `blockstackAPIUrl` field.

### CODE REVIEW

**Comment by kantai** [comment]
@jcnelson -- you should add more description to this PR on how a reviewer can do end-to-end testing. For changes in auth, unit tests aren't usually enough, as they generally end up having a lot of end-to-end effects -- does this continue to validly authenticate the prior version of blockstack.js when its linked into the browser? Do applications which link this in continue to work when they try to authenticate with the previous version of the browser (which links blockstack 17.2.0)?

**Comment by larrysalibra** [comment]
+1 to @kantai 's questions.

**Comment by jcnelson** [comment]
Hey @kantai, @larrysalibra,

I spent some time setting up a live test for this PR. If you go to http://35.231.45.59:1800, you can sign into a "Hello Blockstack" app with `blockstack.js 18.x`, and if you go to http://35.231.45.59:1900, you can sign into a "Hello Blockstack" app with this PR applied.

The "Hello Blockstack" app I wrote to test this PR can be found here: https://github.com/jcnelson/blockstack-auth-test-app.  It will let you inspect various things in the `authResponse` token generated by an authenticator (e.g. the Browser, the CLI) and will test `getFile()`, `putFile()`, and `lookupProfile()` and friends with the Gaia hub and/or Core API endpoint given in the `authResponse`.

To test this PR, you would verify four things:
* You can sign into the version with blockstack.js 18.x with an authenticator using version 1.2.
* You can sign into the version with blockstack.js 19.x with an authenticator using version 1.2.
* You can sign into the version with blockstack.js 18.x with an authenticator using version 1.3.
* You can sign into the version with blockstack.js 19.x with an authenticator using version 1.3.

You can test `authResponse` 1.2 with the Blockstack Browser.  You can test `authResponse` 1.3 with the CLI by running:

```
$ blockstack-cli -H YOUR_CORE_ENDPOINT authenticator YOUR_GAIA_WRITE_ENDPOINT YOUR_BACKUP_PHRASE
```

Specific to testing version 1.3 of the `authResponse`, you should be able to run the `develop` branch of the Gaia hub, and you should be able to use my test apps with only your ID-address whitelisted.  This is because the CLI will generate an `associationToken` for the Gaia hub that will allow you to automatically authorize your app-specific keys.  An easy way to do this is to run the Gaia hub locally, with this [gaia.conf](https://github.com/jcnelson/blockstack-auth-test-app/blob/test/blockstack-19.x/bin/gaia.conf).  You can run a read endpoint for the Gaia hub that will set your CORS headers correctly using this program [here](https://github.com/jcnelson/blockstack-auth-test-app/blob/test/blockstack-19.x/bin/gaia-read.py).

For example, the full sequence of steps to test `authResponse` 1.3 with all local endpoints would be to do the following (to a first approximation):

```bash
# start local API endpoint
$ blockstack --debug api start

# start local Gaia hub
$ blockstack-gaia-hub /path/to/your/gaia.conf

# start local Gaia read endpoint and CORS proxy
$ gaia-read.py /path/to/your/gaia.conf

# start CLI authenticator to store your app data to localhost, but still store your (updated)
# profile to hub.blockstack.org
$ blockstack-cli -H http://localhost:6270 http://localhost:4001 "YOUR-12-WORDS" https://hub.blockstack.org
```

Then, you should be able to log into http://35.231.45.59:1900 and see your custom Core endpoint and Gaia hub, and you should see your login counters written (and later fetched) to and from your local Gaia hub.  You should also see name lookups hit your local Core node.  Your profile should be updated on `hub.blocktack.org` to contain a new `apps` entry for `http://35.231.45.59:1900`, and it should point to `http://localhost:4001`.

**Comment by larrysalibra** [comment]
Plan to take a look at this tomorrow!

**Review by kantai — COMMENTED** [review]
The code looks good to me. I will test this in a couple different login flows today.

**Review by kantai — APPROVED** [review]
Tested with blockstack-todos and blockstack-browser master via:

```
todos linked to feature/authResponse-1.3 + browser as is in master
todos linked to feature/authResponse-1.3 + browser linked to feature/authResponse-1.3
todos as in master + browser linked to feature/authResponse-1.3
```
All three login flows worked as expected.

**Review by larrysalibra — APPROVED** [review]
Thanks so much for this @jcnelson !

This looks good to me - I added a change log entry. Please feel free to revise it if you don't think it properly reflects the changes.

**Comment by larrysalibra** [comment]
@jcnelson Please merge this if the the change log looks good to you!

**Comment by jcnelson** [comment]
Looks good to me!  Thanks for reviewing!

**Pull request merged**
