### PR TITLE
Support additional types in putFile

### PR DESCRIPTION
**Pull request by zone117x**
Closes https://github.com/blockstack/blockstack.js/issues/689

Adds support for [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File), [`Blob`](https://developer.mozilla.org/en-US/docs/Web/API/Blob), and [`TypedArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray)s  to the `putFile` function. 

When encryption is not enabled, the stream types are sent directly through to the `fetch` POST body and streamed from disk -> network when appropriate. 

However, this PR does *not* improve the encryption related issues. When encryption is enabled, the stream types are buffered into memory, then encrypted and POSTed. 

Support for the `ReadableStream` type is blocked by web browsers having yet to implement https://github.com/whatwg/fetch/pull/425. 

[jsdom](https://github.com/jsdom/jsdom) is used in the unit tests to polyfill the DOM File APIs

### Acceptance criteria
* Ensure no regressions `putFile` and `getFile`.
* Test `putFile` with [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) objects -- opened a PR with several example usages of this here https://github.com/blockstack/blockstack-app-generator/pull/65 as well as a live demo here https://zone117x.github.io/blockstack-file-api-demo/dist/index.html

### CODE REVIEW

**Comment by stackatron** [comment]
@zone117x needs to add some testing criteria for @timstackblock

**Comment by zone117x** [comment]
@timstackblock @yknl Created a draft PR against the app-generator with example usages -- see the updated PR acceptance criteria for links

**Review by yknl — APPROVED** [review]
LGTM

**Comment by timstackblock** [comment]
@zone117x The app-generator PR was helpful looks good so far I should be finish with this shortly

**Comment by timstackblock** [comment]
This is complete and test passed

**Review by timstackblock — APPROVED** [review]

**Pull request merged**
