### PR TITLE
Dev UX / Packaging upgrades

### PR DESCRIPTION
**Pull request by zone117x**
Reference issue: https://github.com/blockstack/blockstack.js/issues/580

Fixes:
* https://github.com/blockstack/blockstack.js/issues/580
* https://github.com/blockstack/blockstack.js/issues/534
* https://github.com/blockstack/blockstack.js/issues/541

Summary:
* Upgrade to babel 7.
* Compile `src/**/*.js` for usage as a Node.js lib - using minimal babel transforms. Essentially just transforming module syntax from es6 to Node/CommonJS. Fixes editor intellisense/code-completion in many cases.
* Compile `dist/blockstack.js` using Browserify + babel transforms for good web browser / es2015 support.
* Specify `dist/blockstack.js` in [package.json `browser`](https://docs.npmjs.com/files/package.json#browser) field. Many lightweight web bundlers will use this field. While more complex apps using their own webpacking/bundling can continue to use the lib contents from `"main": "lib/index"`. 
* nyc and tape are now ran directly against the Flow src as recommended by the package authors.
* Code coverage reporting for original `src` files to codecov.io.

E2E tests with auth-browser ran and passed:
```
npm i blockstack@blockstack/blockstack.js#feature/packaging-upgrades
npm run test-e2e:localBuild
```

### CODE REVIEW

**Comment by zone117x** [comment]
Regarding failing CI - pretty sure the node/npm version needs updated to latest LTS. Full paths should not be required to run npm binaries/modules (`./node_modules/babel/idk.js args..` vs `babel args..`)

**Comment by zone117x** [comment]
Ping reviewers - this is ready for review.

**Comment by kantai** [comment]
This worked for me when I linked it into an application.

Thanks for cleaning all of this up, @zone117x !

**Review by kantai — APPROVED** [review]

**Review by yknl — APPROVED** [review]
Looks great to me 👍 Thanks!

**Pull request merged**
