### PR TITLE
Hotfix/namespace burn address

### PR DESCRIPTION
**Pull request by jcnelson**
The burn address for a namespace is chosen by its `version` field.  `version === 1` means "burn to the default burn address", and `version === 2` means "burn to the namespace's `address` value".  This PR fixes this behavior in `network.js` and fixes the operations unit test to test for this behavior.

### CODE REVIEW

**Comment by kantai** [comment]
This looks clear enough to me -- isn't there an additional condition here though? If the namespace is `v2` and older than a year, the burn address switches back to the default, right?

**Comment by jcnelson** [comment]
Right, thanks for clarifying.  Will make that change too.

**Comment by jcnelson** [comment]
Pushed a fix to ensure that the right burn address gets returned at <1, =1, and >1 years after a pay-to-namespace-creator namespace is revealed.

**Review by kantai — APPROVED** [review]
Looks great, thanks @jcnelson

**Pull request merged**
