### PR TITLE
feat: storage calls without user session

### PR DESCRIPTION
**Pull request by yknl**
This PR allows storage calls without having a signed in user session.

https://github.com/blockstack/blockstack.js/issues/802

For details refer to issue #123

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [x] Changelog is updated
- [x] Tag 1 of @yknl or @zone117x for review

### CODE REVIEW

**Comment by markmhendrickson** [comment]
This change seems straightforward enough. @yknl do you want me to test this as an integration in my app specifically or are you confident it'll work there?

**Comment by yknl** [comment]
@markmhx  Yes, we can wait until you've had a chance to test it with your app, just want to make sure it resolves the issue for you.

**Review by hstove — APPROVED** [review]
Would love to see a test here but :+1:

**Comment by markmhendrickson** [comment]
It appears that the `userSession` object is always available in this function, even if there's no actual session with related `userData` available. As such this conditional doesn't catch the lack of user data before reaching the need to retrieve a `coreNode` value on line 1321:

Screen Shot 2020-11-11 at 21 02 22

**Review by markmhendrickson — CHANGES_REQUESTED** [review]
This conditional doesn't seem to resolve the underlying problem with calling this function when no session user data is available.

**Comment by markmhendrickson** [comment]
This appears to be affecting the todos app as well https://github.com/blockstack/todos/issues/55

**Comment by agraebe** [comment]
closing this for now. please re-open if you think this requires attention. if you re-open, please also suggest who could help resolve and carry it to the finish line 🙏🏼

**Pull request closed without merging**
