### PR TITLE
[WIP] Feature/toolchain updates

### PR DESCRIPTION
**Pull request by zone117x**
Upgrade toolchain related packages after recent significant updates:
* Using official typescript->babel->webpack setup with the introduction of [Babel 7.4.0 w/ Typescript 3.4](https://babeljs.io/blog/2019/03/19/7.4.0). 
* [core-js v3 w/ babel](https://github.com/babel/babel/pull/7646) - ability to polyfill instance methods without polluting global scope. 
* Bugs & improvements in `typescript-eslint`. 

One of the main things this does is let us use ecmascript_X features that may be available in supported Node.js runtimes but unavailable in the web browsers that we want the dist bundle to support. Especially new APIs on built-ins types.

### CODE REVIEW

**Comment by yknl** [comment]
Is there a minimum node version requirement? When I use node v8.12 I get an error running webpack. But it works with v10.13.

**Review by hstove — APPROVED** [review]
This looks good to me, and I appreciate some of the refactoring towards `await` and away from `.then` chains.

**Review by yknl — APPROVED** [review]

**Comment by zone117x** [comment]
Note: various parts of this toolchain have gone through additional rapid iteration and this PR needs updating and additional testing before merging.

**Comment by zone117x** [comment]
Closing. Many of the changes in this PR have since been performed iteratively in other PRs. The `core-js v3 w/ babel` update now makes more sense to do in a new PR.

**Pull request closed without merging**
