### PR TITLE
feat(cli): gen keychain with custom path

### LINKED ISSUE #918: Support custom derivation paths with CLI
Hiro DevOps has two addresses which were created on the V1 network before the V2 mainnet launch using the old `blockstack-cli`, and had some BTC and STX sent to these addresses. Because of this, they were created on the old derivation path which is not supported on the Stacks Wallet.

How can someone access the funds on old addresses created using the old derivation path through any means?

### PR DESCRIPTION
**Pull request by kyranjamie**
@CharlieC3 we need something like this to support custom derivation paths

Ideally the cli could use some arg parsing library than arg indexes, I guess this came from the previous version.

I have not tested this code. Wanted to make as a quick placeholder PR for solving issue mentioned here https://github.com/blockstack/stacks-wallet/issues/544

### CODE REVIEW

**Comment by agraebe** [comment]
@kyranjamie what would be the next step here?

**Comment by kyranjamie** [comment]
@agraebe To be honest, I made this PR to be as helpful as possible, while falling just short of volunteering to do it myself 😅 . 

It needs to be finished and tested. I can pick it up if needed, or someone else can. Is it an immediate priority?

**Comment by zone117x** [comment]
A unit test for this would be helpful, add to the extensive cli unit tests here 😄 
https://github.com/blockstack/stacks.js/blob/5f4d2517efd080261879fd6df33b2cfb7524d65f/packages/cli/tests/cli.test.ts#L1-L3

**Comment by agraebe** [comment]
@kyranjamie to your point of priority - I believe we settled on this being low priority in the issue discussion.

I simply would like to avoid stale PRs. If we have a low-effort way to completing this, we should. If it is more involved, I'd suggest we close this PR and get to the issue once it becomes more relevant.

**Comment by kyranjamie** [comment]
Alright, let's close it out. 

I'm sure it's doable without huge efforts, but I think the whole development cycle, start through release, is move involved than to just a quick fix now.

**Pull request closed without merging**
