### PR TITLE
chore: remove duplicate profile definition

### LINKED ISSUE #1382: Remove duplicate Profile type definition
**Describe the bug**
Wallet-sdk defines a profile type. This should be part of @stacks/profile. With #1381 we then have two type definitions.

**What version of Stacks.js are you using?**
HEAD

**Additional context**
https://github.com/hirosystems/stacks-wallet-web/pull/2632

### PR DESCRIPTION
**Pull request by janniks**
> This PR was published to npm with the version `6.5.2-pr.acbc1ce.0`
> e.g. `npm install @stacks/common@6.5.2-pr.acbc1ce.0 --save-exact`

- closes #1382

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]

**Comment by friedger** [comment]
This change would limit the update to person profile. However, the API should support any profile , like organisation profile or app profile

**Review by friedger — CHANGES_REQUESTED** [review]
The API should support more than person profiles

**Comment by janniks** [comment]
> The API should support more than person profiles

Right, [does using the ProfileBase do the trick](https://github.com/hirosystems/stacks.js/compare/0428ea83def58ad53f85654bea155ae1466e9941..6594e01dd46b6a67134b06d38d9b3ddae0eef779)? For this API we would want to allow anything, right? There is no schema validation happening here anyway.

**Review by kyranjamie — APPROVED** [review]

**Review by friedger — APPROVED** [review]

**Comment by friedger** [comment]
ProfileBase looks good.
LGTM

**Pull request merged**
