### PR TITLE
Update custom protocol handler library to fix issues on chrome os

### PR DESCRIPTION
**Pull request by larrysalibra**
Use updated library to incorporate these changes: https://github.com/larrysalibra/custom-protocol-detection/pull/1 from @brandonparee to fix Chrome OS https://github.com/blockstack/blockstack-browser/issues/1269

### CODE REVIEW

**Comment by larrysalibra** [comment]
Tested this on my mac to make sure it didn't break existing functionality using blockstack-todos:

on this branch:
`npm link`
`cd ../blockstack-todos`
`npm link blockstack`

Then run the todos app locally and try signing in.

**Review by kantai — APPROVED** [review]
Tested this with blockstack-todos, and this works for me in Firefox and Chrome.

**Comment by larrysalibra** [comment]
Thank you @kantai

**Comment by seb-langen** [comment]
is not fixed yet?

**Pull request merged**
