### PR TITLE
feat: add regtest to list of available networks

### LINKED ISSUE #1041: Network: Add regtest to list of available networks
Our network package exposes mainnet, testnet, and mocknet networks. However, we do not have the regtest in this list: https://github.com/blockstack/stacks.js/blob/master/packages/network/src/index.ts#L99.

Regtest is available at: `https://stacks-node-api.regtest.stacks.co/`

cc @kyranjamie @reedrosenbluth

### PR DESCRIPTION
**Pull request by agraebe**
fixes #1041

## Type of Change
- [X] New feature
- [ ] Bug fix
- [X] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
- Docs updates generated
- Readme updates included

## Checklist
- [ ] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [ ] `npm run test` passes
- [ ] Changelog is updated
- [X] Tag for review

### CODE REVIEW

**Comment by agraebe** [comment]
Looks like the docs were not generated in the last updates, so most file changes are related to that.

The specific change is only a few lines: https://github.com/blockstack/stacks.js/pull/1043/files#diff-b8c39b8b5b7a349e46b4af548b87b41af27cb8cd36c1de865f1a109025461b9cR110

**Review by kyranjamie — APPROVED** [review]
LGTM—just checking all the `doc/` changes are supposed to be there too? 🤔

**Comment by agraebe** [comment]
@reedrosenbluth could you help review if the docs changes are supposed to be there? I think this is because the last release didn't include docs updates (a lot of docs updates are unrelated to the code change in this PR).

**Comment by reedrosenbluth** [comment]
@agraebe I think that's correct. we should really have a GH action for generating updated docs whenever a new build is released. I'll make an issue for this

**Comment by reedrosenbluth** [comment]
https://github.com/blockstack/stacks.js/issues/1047

**Review by reedrosenbluth — APPROVED** [review]

**Pull request merged**
