### PR TITLE
Adds expiry time to authToken header sent in connectToGaiaHub call

### PR DESCRIPTION
**Pull request by mascot6699**
Use the following template to create your pull request

## Description

With the current state of code it feels like the token returned by `makeV1GaiaAuthToken` has the possibility of reuse and thus hides the optional functionality of expiry of token which can be set as specified by Gaia.
If the `payload` has the optional `exp` params while creating the token using `makeV1GaiaAuthToken` then gaia's [validate token](https://github.com/blockstack/gaia/blob/73409ca31e0f203d352e9f4851adf3898b0f21da/hub/src/server/authentication.ts#L362) function can correctly identify if token is expired/reuse is possible.

By this change no current applications will be impacted but as a Blockstack developer who wish to create token with higher security bar(by specifying its expiry) can do so, thus preventing any misuse of token via replay attacks. This functionality is particularly useful for creating apps which requires privateKeyHolders approval for each gaia upload call.

For details refer to issue #123

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
n/a

## Are documentation updates required?
Yes

## Testing information

Provide context on how tests should be performed.

This can be tested for making a gaia upload call with token which is already expired (i.e call `connectToGaiaHub` with negative `tokenValidityBufferTime`) and it should return 401 with response similar to 
```
{
    "message": "Expired authentication token: expire time of xxxxxxx (secs since epoch)",
    "error": "ValidationError"
}
```
Also testing that `connectToGaiaHub` call without `tokenValidityBufferTime` remains as it is.

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [ ] Changelog is updated
- [x] Tag 1 of @yknl or @zone117x for review

### CODE REVIEW

**Comment by friedger** [comment]
See also https://github.com/blockstack/docs.blockstack/issues/151 (and maybe https://github.com/blockstack/blockstack.js/issues/607)

**Review by zone117x — APPROVED** [review]
Tested this and works as expected, thanks!

**Review by timstackblock — APPROVED** [review]

**Comment by zone117x** [comment]
@mascot6699 can you revert the changes made after my PR review? We cannot merge this with the recent changes that are unrelated to the goal of the PR.

**Comment by agraebe** [comment]
closing this for now. please re-open if you think this requires attention. if you re-open, please also suggest who could help resolve and carry it to the finish line 🙏🏼

**Pull request closed without merging**
