### PR TITLE
Updates to the javadocs

### PR DESCRIPTION
**Pull request by moxiegirl**
- Removing private methods after discussion wit Aaron
- Including AUTHENTICATION,PROFILE,STORAGE content instead of sending users to repo
- Adjusting AUTHENTICATION,PROFILE,STORAGE markdowns to work in gen'd docs

Signed-off-by: moxiegirl <mary@blockstack.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@larrysalibra @kantai This has the removal of the private methods.  Can y'all take a look?

**Comment by larrysalibra** [comment]
@moxiegirl I think this is a duplicate of this pull request: 
https://github.com/blockstack/blockstack.js/pull/520

**Comment by moxiegirl** [comment]
@larrysalibra This has some additions actually. In the config.  Why don't you pull #520 and I'll rebase this one. That way you can see the changes.

**Comment by larrysalibra** [comment]
@moxiegirl i merged #520 into master - feel free to rebase at your leisure!

**Comment by moxiegirl** [comment]
@larrysalibra Give it a look. All rebased.

BTW, The objects AUTHENTICATION, PROFILE, STORAGE are all now links. No longer sending folks out to github for these.

**Review by larrysalibra — APPROVED** [review]
this is excellent! a huge improvement! thanks @moxiegirl !!

**Pull request merged**
