### PR TITLE
Fix null handling problems with encryption

### PR DESCRIPTION
**Pull request by kantai**
Simple fix for Issue #320 -- if the return file is `null` (happens on 404), don't try to decrypt it, just return `null`.

### CODE REVIEW

**Review by larrysalibra — APPROVED** [review]
Works for me!

**Review by larrysalibra — CHANGES_REQUESTED** [review]
Can you add test coverage for this behavior?

**Comment by kantai** [comment]
We'll need to add support for localStorage to the test framework I think.

**Comment by larrysalibra** [comment]
@kantai we've used this to mock localstorage elsewhere https://www.npmjs.com/package/node-localstorage

**Comment by kantai** [comment]
I was planning on using this package:

https://www.npmjs.com/package/mock-local-storage

But `node-localstorage` looks like it'll work too

**Comment by kantai** [comment]
I went with `mock-local-storage`, because `node-local-storage` uses the local file system, and I don't want the test to depend on the file system.

**Comment by larrysalibra** [comment]
Thanks for the tests @kantai!

**Pull request merged**
