### PR TITLE
Create update-profile.md

### PR DESCRIPTION
**Pull request by friedger**
> This PR was published to npm with the version `6.5.5-pr.425e151.0`
> e.g. `npm install @stacks/common@6.5.5-pr.425e151.0 --save-exact`

## Description

Since version 7.1 @stacks/connect supports profile update requests. This PR adds a new feature guide for updating profiles.

### CODE REVIEW

**Review by janniks — APPROVED** [review]
I like these changes, should we merge?

**Comment by friedger** [comment]
Lgtm

**Comment by friedger** [comment]
@janniks merge conflicts have been resolved

**Comment by janniks** [comment]
`This branch cannot be rebased due to conflicts` 
Can you try again, otherwise I can also fork and merge from there? (commitlint is fine, we can ignore that x)

**Comment by friedger** [comment]
A created a new PR: https://github.com/hirosystems/stacks.js/pull/1529

**Pull request closed without merging**
