### PR TITLE
feat(transactions): export cvToHex, hexToCV, parseReadOnlyResponse

### PR DESCRIPTION
**Pull request by friedger**
## Description

As a blockstack developer, I would like to use the blockstack-api-client library. The method `SmartContractsApi.callReadOnlyFunction` requires to hex encode clarity values, the result of that method needs to be parsed. In  this library (`stacks-transactions-js`) these methods already exists.

These methods, defined in `utils.ts` are now exported.

For details refer to issue https://github.com/blockstack/stacks-transactions-js/issues/126

## Type of Change
- [x] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
yes, documentation for new methods needs to be published

## Testing information
No code features changed.

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` in transactions passes
- [ ] Changelog is updated - where is that?
- [x] Tag @yknl for review

### CODE REVIEW

**Review by yknl — APPROVED** [review]
Thanks for copying over!

**Comment by agraebe** [comment]
Where will these methods be documented? We currently don't have any documentation for them. In the txjs repo, we would use the README file. @yknl - will these methods be in the new docs for the monorepo?

**Comment by yknl** [comment]
There are typedoc generated reference docs but it's better to have it in the form of a smart contract tutorial.

**Comment by agraebe** [comment]
@friedger could you add some docs updates for this PR?

**Comment by friedger** [comment]
I have provided the documentation in the code. @agraebe isn't it enough to regenerate the docs? I'm using these methods also in the tutorial

**Comment by agraebe** [comment]
I think I wanted to make a broader point for documentation inside our docs as opposed to just inside typedoc. most developers will find it very buried if it is only mentioned in the typedoc. I think it's okay if we tackle the broader issue outside of this PR. 

The only relevant place I can think of (right now) would be https://docs.blockstack.org/stacks-blockchain/integrate-stacking#step-6-display-stacking-status

**Review by yknl — APPROVED** [review]

**Pull request merged**
