### PR TITLE
Web Crypto APIs

### PR DESCRIPTION
**Pull request by zone117x**
## Description

Closes https://github.com/blockstack/blockstack.js/issues/691

The goal of this PR is to make the cryptographic operations performed by blockstack.js more efficient -- less CPU & memory intensive and smaller file size (especially for mobile). 

This primarily improves the performance of storage and authentication functions. 

This PR includes a refactor of all usages of applicable cryptographic operations to use the W3C native Web Crypto APIs. 

This includes:
* `aes-256-cbc` encrypt & decrypt
* `sha-256` and `sha-512` hash digests 
* `hmac-sha256` digest
* `pbkdf2-sha256` and `pbkdf2-sha512` password derivation

The `ripemd160` hash digest is not available in the Web Crypto API, however, it has been converted to use a minimal and relatively fast JS lib as opposed to the large node.js `crypto` module polyfill. 

The `triplesec` lib is no longer a direct blockstack.js dependency. It must now be provided by the consumer application. It was responsible for ~250KB of the blockstack.js dist, but is used only for decrypting legacy mnemonics. AFAIK no regular apps built on Blockstack use this. Only a few consumer apps use this function (e.g. blockstack-cli, blockstack-browser, wallet[?]). It has been made trivial for consumer apps to import the `triplesec` lib and pass it to blockstack.js. 

The `cheerio` html parsing lib has the same treatment as above. It is used for social proofs, which is not directly used by typical apps. Consumer apps (e.g. Gaia, blockstack-browser) must import this dependency themselves. 

The dist bundle size is now down to 550KB. 

The linter rules were tightened up, especially around Promise/async/await handling. This helped catch several instance of bugs like `` `some_string_${promise_variable}` `` -> `` `some_string_${await promise_variable}` ``. The stricter rules also ended up requiring minor changes to some code that is not necessarily related to cryptographic operations. 

For updates on our effected consumer apps, see:
* https://github.com/blockstack/blockstack-browser/pull/1966
* https://github.com/blockstack/blockstack-keychain/pull/10
* https://github.com/blockstack/cli-blockstack/pull/27
* https://github.com/blockstack/gaia/pull/272

## Type of Change
- [x] New feature
- [x] API reference/documentation update

## Does this introduce a breaking change?
This is a breaking change and requires a major version update. 

_Note: the Web Crypto APIs only provide async functions, so the changes to use these propagated up to several other functions in the call graphs._  

I kept a list of all functions that were previously synchronous which now return promises. Most of these are not public API functions. These have been listed in the CHANGELOG: 
```
handleSignedEncryptedContents
makeAuthResponse
encryptECIES
decryptECIES
encryptPrivateKey
decryptPrivateKey
encryptContent
decryptContent
aes256CbcEncrypt
aes256CbcDecrypt
hmacSha256
```

## Are documentation updates required?
Possibly -- the API reference docs will be auto updated, but any tutorials referencing the above functions may need updated.

## Checklist
- [x] Code is commented where needed
- [x] Unit test coverage for new or modified code paths
- [x] `npm run test` passes
- [x] Changelog is updated
- [x] Tag 1 of @yknl or @zone117x for review

## Extra TODO
- [ ] Ensure working on all supported browsers: Chrome, Firefox, Safari, Edge
  - (?) Determine minimum supported versions for each browser.

### CODE REVIEW

**Comment by zone117x** [comment]
TODO: 
Many of the minor helper functions that have been made async, for example `publicKeyToAddress`, still have the synchronous hashing and EC dependencies available due to `bitcoinjs-lib` & family. 
These helper functions can have deprecatable sync version re-implemented, e.g. `publicKeyToAddressSync`, in order to help with migrating some of the upstream dependent applications.

**Comment by yknl** [comment]
Thanks @zone117x for all the work on this PR. It looks mostly good for me, but I think the latest changes broke some of the tests. I'm getting 12 failed tests right now, mostly on the RIPEMD160 and SHA2 hash tests.

**Comment by zone117x** [comment]
@yknl If you are still running into test failures, can you ensure Node.js >=10 is being used, and try wiping your `node_modules` directory and re-running `npm i`. 
I just tested with both Node v10 and v12, and all tests are passing. Also just pushed a fix for v8 which allows all tests to pass.

**Review by yknl — APPROVED** [review]
LGTM

**Comment by diwakergupta** [comment]
@zone117x looks like this has been approved a while back, any other blockers to merging?

**Review by timstackblock — APPROVED** [review]

**Pull request merged**
