### PR TITLE
Include manifestURI in manifest object

### PR DESCRIPTION
**Pull request by friedger**
This PR
* adds property `manifestURI` to the loaded manifest object

Applications want to know where the manifest came from, for example https://github.com/blockstack/blockstack-browser/issues/1783

### CODE REVIEW

**Comment by yknl** [comment]
I'm not totally understanding the use case for this, the application has the ability to specify the manifestURI through `redirectToSignIn()`.

**Comment by friedger** [comment]
@yknl when I ask blockstack.js to decode a jwt and fetch the manifest I do not know where the manifest came from. Issue 1875 of the browser is my use case

**Comment by yknl** [comment]
Ok got it, this is so that the Blockstack browser can handle relative app icon URLs not for applications.

**Comment by friedger** [comment]
I thought the browser is an app.

**Comment by yknl** [comment]
That's true 👍

**Comment by zone117x** [comment]
@friedger can you merge develop into this PR?

**Comment by friedger** [comment]
@zone117x Done :-)

**Review by zone117x — APPROVED** [review]
LGTM

**Review by yknl — APPROVED** [review]

**Pull request merged**
